Repository dnd-side-project/dnd-10th-3-backend, pull requests merged in 2024-03, with the labels that each got.

#125 [FEAT] 투표 공감 기능 구현
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/domain/entity/VoteLike.java
  src/main/java/dnd/donworry/repository/VoteLikeRepository.java
  src/main/java/dnd/donworry/repository/custom/VoteLikeRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/VoteLikeRepositoryImpl.java
  src/main/java/dnd/donworry/service/VoteService.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
Labels: ✨ Feature

#127 [REFACTOR] Pages 클래스 변수 명 변경
  src/main/java/dnd/donworry/domain/dto/comment/Pages.java
Labels: 🔨 Refactor

#128 [BUGFIX] 공감 취소 반영
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
Labels: 🐞 Bug fix

#129 [FEAT] 투표 검색 API 구현
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/domain/dto/comment/Pages.java
  src/main/java/dnd/donworry/domain/dto/vote/VotePagingDto.java
  src/main/java/dnd/donworry/repository/custom/VoteRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/VoteRepositoryImpl.java
  src/main/java/dnd/donworry/service/VoteService.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
Labels: ✨ Feature, 📬 API

#131 [FEAT] 댓글 전체 조회 API 개발
  src/main/java/dnd/donworry/controller/CommentController.java
  src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java
  src/main/java/dnd/donworry/service/CommentService.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
Labels: ✨ Feature, 📬 API

#133 [REFACTOR] 투표 검색 기능 비 로그인 유저도 사용 가능 하게 security config 설정에 추가
  src/main/java/dnd/donworry/config/SecurityConfig.java
Labels: 🔨 Refactor

#135 [PERFORMANCE] 댓글 전체 조회 시 발생하던 N+1 문제 수정
  src/main/java/dnd/donworry/domain/entity/Comment.java
  src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
Labels: 🔨 Refactor, 📬 API, 🚨 Bug report

#141 [FEAT] 유저 정보 조회 API 개발
  src/main/java/dnd/donworry/controller/UserController.java
  src/main/java/dnd/donworry/domain/dto/user/UserResponseDto.java
  src/main/java/dnd/donworry/service/UserService.java
  src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
Labels: ✨ Feature, 📬 API

#142 [REFACTOR] 카카오 redirect-Url 프론트 vercel로 action 변경
  src/main/java/dnd/donworry/controller/OauthController.java
Labels: 🌏 Deploy
