Repository dnd-side-project/dnd-10th-3-backend, pull requests merged in 2024-02, with the labels that each got.

#25 [FEAT] 연관관계 매핑
  .gitignore
  src/main/java/dnd/donworry/DonworryApplication.java
  src/main/java/dnd/donworry/domain/BaseEntity.java
  src/main/java/dnd/donworry/domain/Comment.java
  src/main/java/dnd/donworry/domain/CommentLike.java
  src/main/java/dnd/donworry/domain/OptionImage.java
  src/main/java/dnd/donworry/domain/Selection.java
  src/main/java/dnd/donworry/domain/User.java
  src/main/java/dnd/donworry/domain/UserVote.java
  src/main/java/dnd/donworry/domain/Vote.java
  src/main/java/dnd/donworry/domain/VoteLike.java
Labels: ⚙ Setting

#27 [SET] yml 분리 및 AWS 저장소 연결
  .gitignore
  build.gradle
  src/main/java/dnd/donworry/config/S3Config.java
  src/main/java/dnd/donworry/core/factory/YamlPropertySourceFactory.java
  src/main/java/dnd/donworry/core/manager/AWSFileManager.java
  src/main/java/dnd/donworry/core/manager/FileManager.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#28 ✨ ResponseCode , errorCode setting
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResResult.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
Labels: ✨ Feature

#30 [BUGFIX] ErrorCode 빌드 에러 수정
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
Labels: 🐞 Bug fix

#31 🚀 Workflow 파일 수정
  .github/workflows/gradle.yml
Labels: 🐞 Bug fix, 🌏 Deploy

#32 🚀 Workflow 파일 수정
  .github/workflows/gradle.yml
Labels: ⚙ Setting

#34 [FEAT, TEST] 테스트 API 구현
  src/main/java/dnd/donworry/controller/TestController.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResResult.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/test/TestRequestDto.java
  src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java
  src/main/java/dnd/donworry/domain/entity/TestResult.java
  src/main/java/dnd/donworry/exception/CustomException.java
  src/main/java/dnd/donworry/exception/ExceptionHandleFilter.java
  src/main/java/dnd/donworry/exception/GlobalExceptionHandler.java
  src/main/java/dnd/donworry/manager/TestManager.java
  src/main/java/dnd/donworry/service/TestService.java
  src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
  src/test/java/dnd/donworry/manager/TestManagerTest.java
Labels: ✨ Feature, ✅ Test, 📬 API

#36 [FEAT] 투표 생성 API 구현
  .gitignore
  build.gradle
  src/main/java/dnd/donworry/config/QuerydslConfig.java
  src/main/java/dnd/donworry/controller/TestController.java
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/core/manager/AWSFileManager.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/selection/SelectionRequestDto.java
  src/main/java/dnd/donworry/domain/dto/selection/SelectionResponseDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteRequestDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/entity/OptionImage.java
  src/main/java/dnd/donworry/domain/entity/Selection.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/repository/OptionImageRepository.java
  src/main/java/dnd/donworry/repository/SelectionRepository.java
  src/main/java/dnd/donworry/repository/Support/Querydsl4RepositorySupport.java
  src/main/java/dnd/donworry/repository/VoteRepository.java
  src/main/java/dnd/donworry/repository/custom/SelectionRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/SelectionRepositoryImpl.java
  src/main/java/dnd/donworry/service/VoteService.java
  src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
  src/test/java/dnd/donworry/service/impl/VoteServiceImplTest.java
Labels: ✨ Feature, ✅ Test, 📬 API

#37 [BUGFIX] Swagger https 적용
  src/main/java/dnd/donworry/SwaggerConfig.java
  src/main/java/dnd/donworry/config/SwaggerConfig.java
Labels: 🐞 Bug fix, 🌏 Deploy

#42 [FIX] Multipart octet 에러 수정
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/util/MultipartJackson2HttpMessageConverter.java
Labels: 🐞 Bug fix, 🚨 Bug report

#40 ✨유저 API 구현
  build.gradle
  src/main/java/dnd/donworry/config/JwtConfig.java
  src/main/java/dnd/donworry/config/RedisConfig.java
  src/main/java/dnd/donworry/config/RedisInitializer.java
  src/main/java/dnd/donworry/config/SecurityConfig.java
  src/main/java/dnd/donworry/controller/OauthController.java
  src/main/java/dnd/donworry/controller/UserController.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/jwt/TokenDto.java
  src/main/java/dnd/donworry/domain/dto/jwt/TokenResponseDto.java
  src/main/java/dnd/donworry/domain/dto/user/UserDto.java
  src/main/java/dnd/donworry/domain/dto/user/UserRequestDto.java
  src/main/java/dnd/donworry/domain/dto/user/UserResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Comment.java
  src/main/java/dnd/donworry/domain/entity/CommentLike.java
  src/main/java/dnd/donworry/domain/entity/OptionImage.java
  src/main/java/dnd/donworry/domain/entity/RefreshToken.java
  src/main/java/dnd/donworry/domain/entity/Selection.java
  src/main/java/dnd/donworry/domain/entity/User.java
  src/main/java/dnd/donworry/domain/entity/UserVote.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/domain/entity/VoteLike.java
  src/main/java/dnd/donworry/exception/CustomException.java
  src/main/java/dnd/donworry/exception/ExceptionHandleFilter.java
  src/main/java/dnd/donworry/exception/GlobalExceptionHandler.java
  src/main/java/dnd/donworry/jwt/JwtFilter.java
  src/main/java/dnd/donworry/jwt/JwtProvider.java
  src/main/java/dnd/donworry/jwt/OAuthToken.java
  src/main/java/dnd/donworry/jwt/UserAuthentication.java
  src/main/java/dnd/donworry/repository/RefreshTokenRepository.java
  src/main/java/dnd/donworry/repository/UserRepository.java
  src/main/java/dnd/donworry/service/KakaoOauthService.java
  src/main/java/dnd/donworry/service/OauthService.java
  src/main/java/dnd/donworry/service/UserService.java
  src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
  src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
  src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
  src/main/java/dnd/donworry/util/CookieUtil.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
Labels: ⚙ Setting, ✨ Feature, 📬 API

#43 ♻️유저 닉네임 변경 _customException 수정
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
Labels: 🔨 Refactor

#46 [FEAT] 사전질문 컬럼 추가
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/PreQuestion_AGE.java
  src/main/java/dnd/donworry/domain/constants/PreQuestion_Gender.java
  src/main/java/dnd/donworry/domain/dto/test/TestRequestDto.java
  src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java
  src/main/java/dnd/donworry/domain/entity/TestResult.java
Labels: 🔨 Refactor

#48 [FEAT] 댓글 생성, 수정, 삭제 API 구현
  FETCH_HEAD
  src/main/java/dnd/donworry/controller/CommentController.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentRequestDto.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Comment.java
  src/main/java/dnd/donworry/repository/CommentRepository.java
  src/main/java/dnd/donworry/service/CommentService.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
  src/test/java/dnd/donworry/service/impl/CommentServiceImplTest.java
Labels: ✨ Feature, ✅ Test, 📬 API

#50 [BUGFIX] 예상치 않은 세미클론이 삽입된 구문오류 수정
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
Labels: 🐞 Bug fix

#51 [FEAT] 댓글 공감 API 개발
  src/main/java/dnd/donworry/controller/CommentController.java
  src/main/java/dnd/donworry/domain/dto/commentLike/CommentLikeResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Comment.java
  src/main/java/dnd/donworry/domain/entity/CommentLike.java
  src/main/java/dnd/donworry/repository/CommentLikeRepository.java
  src/main/java/dnd/donworry/service/CommentService.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
  src/test/java/dnd/donworry/service/impl/CommentServiceImplTest.java
Labels: ✨ Feature, ✅ Test, 📬 API

#54 Refactor/#52 vote refactor
  src/main/java/dnd/donworry/controller/TestController.java
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/domain/constants/Category.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentResponseDto.java
  src/main/java/dnd/donworry/domain/dto/commentLike/CommentLikeResponseDto.java
  src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java
  src/main/java/dnd/donworry/domain/dto/user/UserResponseDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteRequestDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/entity/TestResult.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/repository/UserRepository.java
  src/main/java/dnd/donworry/repository/custom/UserRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/SelectionRepositoryImpl.java
  src/main/java/dnd/donworry/repository/impl/UserRepositoryImpl.java
  src/main/java/dnd/donworry/service/TestService.java
  src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
  src/main/java/dnd/donworry/util/TimeUtil.java
  src/main/resources/application.yml
  src/test/java/dnd/donworry/DonworryApplicationTests.java
  src/test/java/dnd/donworry/manager/TestManagerTest.java
  src/test/java/dnd/donworry/service/impl/CommentServiceImplTest.java
  src/test/java/dnd/donworry/service/impl/VoteServiceImplTest.java
Labels: 🔨 Refactor

#56 [FEAT] 스웨거 유저 생성 기능 구현
  src/main/java/dnd/donworry/config/SecurityConfig.java
  src/main/java/dnd/donworry/controller/OauthController.java
  src/main/java/dnd/donworry/controller/UserController.java
  src/main/java/dnd/donworry/service/OauthService.java
  src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
  src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
Labels: ✨ Feature, 📬 API

#58 [REFACTOR] 테스트 결과 API 분리
  src/main/java/dnd/donworry/config/SecurityConfig.java
  src/main/java/dnd/donworry/controller/TestController.java
  src/main/java/dnd/donworry/domain/dto/test/TestRequestDto.java
  src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java
  src/main/java/dnd/donworry/domain/entity/TestResult.java
  src/main/java/dnd/donworry/service/TestService.java
  src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
Labels: 🔨 Refactor, 📬 API

#59 [FEAT] 투표 CRUD API 구현
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/selection/SelectionRequestDto.java
  src/main/java/dnd/donworry/domain/dto/selection/SelectionResponseDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteRequestDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteUpdateDto.java
  src/main/java/dnd/donworry/domain/entity/Selection.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/service/VoteService.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
Labels: ✨ Feature, 📬 API

#60 [REFACTOR] 마감일 형식 변경
  src/main/java/dnd/donworry/domain/dto/vote/VoteRequestDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
Labels: 🔨 Refactor

#61 [FEAT] 유저투표 API 구현
  src/main/java/dnd/donworry/controller/UserVoteController.java
  src/main/java/dnd/donworry/controller/VoteController.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/userVote/UserVoteRequestDto.java
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Selection.java
  src/main/java/dnd/donworry/domain/entity/UserVote.java
  src/main/java/dnd/donworry/repository/OptionImageRepository.java
  src/main/java/dnd/donworry/repository/UserRepository.java
  src/main/java/dnd/donworry/repository/UserVoteRepository.java
  src/main/java/dnd/donworry/repository/VoteRepository.java
  src/main/java/dnd/donworry/repository/custom/OptionImageRepositoryCustom.java
  src/main/java/dnd/donworry/repository/custom/SelectionRepositoryCustom.java
  src/main/java/dnd/donworry/repository/custom/UserRepositoryCustom.java
  src/main/java/dnd/donworry/repository/custom/UserVoteRepositoryCustom.java
  src/main/java/dnd/donworry/repository/custom/VoteRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/OptionImageRepositoryImpl.java
  src/main/java/dnd/donworry/repository/impl/SelectionRepositoryImpl.java
  src/main/java/dnd/donworry/repository/impl/UserVoteRepositoryImpl.java
  src/main/java/dnd/donworry/repository/impl/VoteRepositoryImpl.java
  src/main/java/dnd/donworry/service/UserVoteService.java
  src/main/java/dnd/donworry/service/VoteService.java
  src/main/java/dnd/donworry/service/impl/UserVoteServiceImpl.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
Labels: ✨ Feature, 📬 API

#62 [FEAT] CORS setting
  src/main/java/dnd/donworry/config/SecurityConfig.java
Labels: ⚙ Setting, ✨ Feature

#65 [FEAT] 투표 결과 페이지 수정
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/RANK.java
  src/main/java/dnd/donworry/domain/dto/test/TestResponseDto.java
  src/main/java/dnd/donworry/domain/entity/TestResult.java
  src/main/java/dnd/donworry/manager/TestManager.java
  src/main/java/dnd/donworry/service/TestService.java
  src/main/java/dnd/donworry/service/impl/TestServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#68 [BUGFIX] Cors 미작동으로 인한 재설정
  src/main/java/dnd/donworry/config/SecurityConfig.java
  src/main/java/dnd/donworry/jwt/JwtFilter.java
Labels: 🐞 Bug fix, 🥰 Accessibility

#69 [BUGFIX] Cors 미작동으로 인한 재설정
  src/main/java/dnd/donworry/config/WebMvcConfig.java
Labels: 🥰 Accessibility, 🌏 Deploy

#70 [BUGFIX] Cors 미작동으로 인한 재설정
  src/main/java/dnd/donworry/config/SecurityConfig.java
  src/main/java/dnd/donworry/config/WebMvcConfig.java
Labels: 🥰 Accessibility, 🌏 Deploy

#71 [BUGFIX] Cors 미작동으로 인한 재설정
  src/main/java/dnd/donworry/config/SecurityConfig.java
Labels: 🐞 Bug fix, 🥰 Accessibility

#77 [REFACTOR] KakaoOauthServiceImpl 필요 없는 세미클론 제거
  src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
Labels: 🔨 Refactor

#78 [REFACTOR]securityConfig login url 수정
  src/main/java/dnd/donworry/config/SecurityConfig.java
Labels: 🔨 Refactor, 🥰 Accessibility

#79 [REFACTOR] Client-Secret 추가
  src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
  src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
Labels: 🔨 Refactor

#80 [REFACTOR] KakaoOauthServiceImpl log 추가
  src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
Labels: 🔨 Refactor

#81 [REFACTOR] access,refreshToken - exp 변경
  src/main/java/dnd/donworry/config/JwtConfig.java
Labels: 🔨 Refactor

#82 [BUGFIX] cors setting 변경
  src/main/java/dnd/donworry/config/CorsConfig.java
  src/main/java/dnd/donworry/config/SecurityConfig.java
Labels: 🐞 Bug fix, 🔨 Refactor

#83 ♻️ Spring Security permitAll() 목록 수정
  src/main/java/dnd/donworry/config/SecurityConfig.java
Labels: 🔨 Refactor

#85 [BUGFIX] 회원가입 시 쿠키의 maxAge가 session으로 나오던 버그 수정
  src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
  src/main/java/dnd/donworry/util/CookieUtil.java
Labels: 🐞 Bug fix, 🔨 Refactor

#89 [FEAT] 회원가입 시 닉네임 랜덤하게 추가
  src/main/java/dnd/donworry/service/impl/KakaoOauthServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#92 [FEAT] 조회수 증가 기능 구현
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/service/impl/VoteServiceImpl.java
Labels: ✨ Feature

#93 [REFACTOR]login 시 토큰과 함께 닉네임도 반환
  src/main/java/dnd/donworry/controller/OauthController.java
  src/main/java/dnd/donworry/domain/dto/user/LoginResponseDto.java
  src/main/java/dnd/donworry/service/OauthService.java
  src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
Labels: 🔨 Refactor

#95 [BUGFIX] 새로고침 시 토큰값이 매번 바뀌던 버그 수정
  src/main/java/dnd/donworry/jwt/JwtFilter.java
Labels: 🐞 Bug fix, 🔨 Refactor

#97 [REFACTOR] cookie delete시 setSecure(true) 추가
  src/main/java/dnd/donworry/util/CookieUtil.java
Labels: 🥰 Accessibility

#99 [FEAT] comment 페이징 ,공감 기능 구현
  src/main/java/dnd/donworry/controller/CommentController.java
  src/main/java/dnd/donworry/domain/constants/Category.java
  src/main/java/dnd/donworry/domain/constants/ErrorCode.java
  src/main/java/dnd/donworry/domain/constants/ResponseCode.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentResponseDto.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentResponseReadDto.java
  src/main/java/dnd/donworry/domain/dto/user/LoginResponseDto.java
  src/main/java/dnd/donworry/repository/CommentLikeRepository.java
  src/main/java/dnd/donworry/repository/CommentRepository.java
  src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java
  src/main/java/dnd/donworry/service/CommentService.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
Labels: ✨ Feature, 📬 API

#105 [REFACTOR] kakao.yml secrets update
  src/main/java/dnd/donworry/controller/CommentController.java
  src/main/java/dnd/donworry/domain/dto/user/LoginResponseDto.java
Labels: 🥰 Accessibility, 🌏 Deploy

#109 [REFACTOR] comment paging 로직 수정
  src/main/java/dnd/donworry/domain/dto/comment/CommentResponseDto.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentResponseReadDto.java
  src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
Labels: 🔨 Refactor

#112 [BUGFIX] refreshToken의 만료 시간이 잘못 설정됨에 따라 코드 수정
  src/main/java/dnd/donworry/config/SecurityConfig.java
  src/main/java/dnd/donworry/jwt/JwtFilter.java
  src/main/java/dnd/donworry/service/impl/OauthServiceImpl.java
  src/main/java/dnd/donworry/service/impl/UserServiceImpl.java
Labels: 🐞 Bug fix

#122 [FEAT] 투표 response에 댓글 개수 추가
  src/main/java/dnd/donworry/domain/dto/vote/VoteResponseDto.java
  src/main/java/dnd/donworry/domain/entity/Vote.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
Labels: ✨ Feature

#124 [REFACTOR] 댓글 페이징 방식 변경
  src/main/java/dnd/donworry/controller/CommentController.java
  src/main/java/dnd/donworry/domain/dto/comment/CommentPagingDto.java
  src/main/java/dnd/donworry/domain/dto/comment/Pages.java
  src/main/java/dnd/donworry/repository/custom/CommentRepositoryCustom.java
  src/main/java/dnd/donworry/repository/impl/CommentRepositoryImpl.java
  src/main/java/dnd/donworry/service/CommentService.java
  src/main/java/dnd/donworry/service/impl/CommentServiceImpl.java
Labels: ✨ Feature
